[project]
name = "usaspending-mcp-server"
version = "0.1.0"
description = "This is an MCP server to interact with the USASPENDING.gov API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anyio>=4.11.0",
    "dotenv>=0.9.9",
    "mcp>=1.16.0",
    "requests>=2.32.5",
    "starlette>=0.48.0",
]
license = "AGPL-3.0-only"
[dependency-groups]
dev = [
    "openai-agents>=0.4.0",
]

[project.scripts]
usaspending-mcp-server = "server:main"

[project.urls]
Repository = "https://github.com/thsmale/usaspending-mcp-server"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "tools",
    "utils",
    "server.py"
]

[tool.hatch.build]
exclude = [
    "test",
    ".vscode",
    "*.md",
]
