[project]
name = "usa-spending-mcp-server"
version = "0.1.0"
description = "This is an MCP server to interact with the USASPENDING.gov API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anyio>=4.11.0",
    "mcp>=1.16.0",
    "requests>=2.32.5",
    "starlette>=0.48.0",
]

[dependency-groups]
dev = [
    "openai-agents>=0.4.0",
]
